### ISSUE TITLE
Trombone Sounds Other Than The Original Are louder than a trombone hooked up to am aux

### ISSUE THREAD

**Issue by Fraisk** [TundraLink/SmoothSound#2]
https://user-images.githubusercontent.com/32005929/198900631-eb9fcfc4-b105-4e0b-829d-669d957f6d05.mp4

Please excuse the quality, the audio's more important, speaking of, gonna put a big old volume warning right here, just in case.

**Comment by TundraLink** [comment]
So, I think I know what's causing this, but the mod is not working in the newest version, so I'm going to try to fix both in the next release if I can

**Comment by TundraLink** [comment]
This issue should now be fixed with the latest release
